name: "Build and sign"
on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'

defaults:
  run:
    working-directory: Extension

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1
      - name: Declare some variables
        shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"

      - name: "web-ext build"
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: .
          filename: "{name}-${{ env.sha_short }}.xpi"
          ignoreFiles: '["package.json", "pnpm-lock.yaml", "./.*", "*.zip", "web-ext-artifcats", "scripts", "src", "README.md", "tsconfig.json"]'

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v3
        with:
          name: "{name}-${{ env.sha_short }}.xpi"
          path: ${{ steps.web-ext-build.outputs.target }}
  sign:
    if: startswith(github.event.ref, 'refs/tags/')
    name: "Release"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "web-ext sign"
        id: web-ext-sign
        uses: kewisch/action-web-ext@v1
        with:
          cmd: sign
          source: ${{ steps.web-ext-build.outputs.target }}
          channel: unlisted
          apiKey: ${{ secrets.AMO_SIGN_KEY }}
          apiSecret: ${{ secrets.AMO_SIGN_SECRET }}
          timeout: 900000

      - name: "Create Release"
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ steps.web-ext-sign.outputs.target }}