name: "Build and sign"
on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  workflow_dispatch:


jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: 'true'

      # PNPM
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install

      - name: Try to remove artifacts folder
        if: ${{ env.ACT }}
        run: rm -rf web-ext-artifacts
        continue-on-error: true

        # Build
      - name: Get last Git SHA
        shell: bash
        run: echo "sha_short=$(printf "%.7s\n" "$(head=($(<.git/HEAD)); cat .git/${head[1]})")" >> "$GITHUB_ENV"
      - name: Build
        run: pnpm run ext:build:ci --filename "lobs_la_conjugaison-${{ env.sha_short }}.xpi"
      - name: Get artifact name
        shell: bash
        run: |
          target=$(cd web-ext-artifacts/ && ls *.xpi -1 | head -n1)
          artifact=$(echo "$target" | cut -d '.' -f1)

          echo "target=$target" >> $GITHUB_ENV
          echo "artifact=$artifact" >> $GITHUB_ENV

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.artifact }}
          path: web-ext-artifacts/${{ env.target }}
          if-no-files-found: error
          retention-days: 7
    outputs:
      artifact: ${{ env.artifact }}
  sign:
    if: startswith(github.event.ref, 'refs/tags/v') && ${{ !github.event.act }}
    name: "Release"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: ${{needs.build.outputs.artifact}}

      - name: "Sign"
        id: web-ext-sign
        uses: kewisch/action-web-ext@v1
        with:
          cmd: sign
          source: ${{needs.build.outputs.artifact}}
          channel: ${{ (github.event_name == 'workflow_dispatch' && 'unlisted') || 'listed' }}
          apiKey: ${{ secrets.AMO_SIGN_KEY }}
          apiSecret: ${{ secrets.AMO_SIGN_SECRET }}
          timeout: 900000

      - name: "Create Release"
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ steps.web-ext-sign.outputs.target }}